### ISSUE TITLE
Set reasonable Tomcat logging defaults

### ISSUE THREAD

**Issue by nephomaniac** [eucalyptus/midokura-cookbook#28]
Tomcat does not appear to have rotate on size properties set for it's logging. Catalina logs can fill the filesystem and will need to have some reasonable max limits set for log file size, count, rotation, etc..

**Comment by nephomaniac** [comment]
tomcat log files are not normally needed, unless troubleshooting tomcat itself is necessary. We can safely disable the massive catalina.out and catalina.yyyy-mm-dd.log files.
1. Disable ConsoleHandler (per https://tomcat.apache.org/tomcat-7.0-doc/logging.html - "Considerations for productive usage"
   Edit /etc/tomcat/logging.properties and replace:
   .handlers = 1catalina.org.apache.juli.FileHandler, java.util.logging.ConsoleHandler
   with:
   .handlers = 1catalina.org.apache.juli.FileHandler
2. Set log level to WARN to avoid unnecessary jersey logs (in /etc/tomcat/logging.properties):
   1catalina.org.apache.juli.FileHandler.level = WARN
3. Disable midonet-api STDOUT, by commenting out the following lines in /usr/share/midonet-api/WEB-INF/classes/logback.xml (this will avoid midonet-api.log entries duplicated in catalina.out)

**Comment by mbacchi** [comment]
Fixed in PR #36
