### ISSUE TITLE
thrift cookbook often fails

### ISSUE THREAD

**Issue by nephomaniac** [eucalyptus/midokura-cookbook#3]
Looks like cassandra is using the thrift cookbook. The Thrift cb is set to use ver 0.9.0 as it's default, but the apache url provided is only providing version 0.9.1 and 0.9.2 so this fails on the checksum. 
We can do a few things to make this work. Here's the thrift cb's default.rb...
Cheers, 
-M

default['thrift']['version']  = '0.9.0'
default['thrift']['mirror']   = 'http://apache.mirrors.tds.net'
default['thrift']['checksum'] = '71d129c49a2616069d9e7a93268cdba59518f77b3c41e763e09537cb3f3f0aac'
default['thrift']['configure_options'] = []

**Comment by viglesiasce** [comment]
Fixed as we no longer depend on the cassandra cookbook

**Comment by viglesiasce** [comment]
Thanks @tbeckham!
